// Generated by https://quicktype.io

export interface Comment {
  commentAuthor: string
  commentAuthorChannel: string
  commentAuthorChannelId: string
  commentAuthorProfilePicture: string
  commentTotalLikeCount: number
  commentId: string
  commentText: string
  commentTimestamp: string
  createdAt: string
  type: string
  videoId: string
}
