/* eslint-disable camelcase */
// Generated by https://quicktype.io

export interface VideoResponse {
  version: string
  thumbnail_height: number
  url: string
  html: string
  provider_url: string
  type: string
  height: number
  title: string
  author_name: string
  thumbnail_url: string
  author_url: string
  provider_name: string
  thumbnail_width: number
  width: number
}
